class AdminTexts:
    TITLE = "Панель администратора"
    MODERATION_TITLE = "Проверка объявлений"
    STATISTICS_TITLE = "Статистика"
    NOTIFICATIONS_TITLE = "Уведомления администратора"
    CHECK_ADS_BUTTON = "Проверить объявления"
    STATISTICS_BUTTON = "Статистика"
    NOTIFICATIONS_BUTTON = "Уведомления"
    BACK_TO_MENU_BUTTON = "Назад в меню"
    ACCESS_DENIED = "Команда доступна только администраторам."

    APPROVE_BUTTON = "Подтвердить"
    REJECT_BUTTON = "Отклонить"
    CANCEL_BUTTON = "Отменить"
    CONFIRM_REJECTION_BUTTON = "Отклонить объявление"

    NO_ADS_ON_CHECK = "Нет объявлений, ожидающих проверки."
    AD_ALREADY_PROCESSED = "Объявление уже проверено другим администратором."
    AD_APPROVED = "Объявление опубликовано."
    AD_REJECTED = "Объявление отклонено."
    REJECTION_CANCELLED = "Отклонение объявления отменено."
    REJECTION_PROMPT = "Отправьте текст с причиной отклонения объявления."
    REJECTION_REQUIRED = "Сначала отправьте причину отклонения."
    REJECTION_TOO_LONG = "Причина не должна превышать 1000 символов."
    REJECTION_SAVED = (
        "Причина сохранена:\n\n{reason}\n\nПодтвердите отклонение объявления."
    )

    APPROVAL_NOTIFICATION = "Ваше объявление опубликовано."
    REJECTION_NOTIFICATION = "Ваше объявление отклонено.\nПричина: {reason}"

    STATISTICS_TEMPLATE = (
        "📊 <b>Статистика использования</b>\n\n"
        "👥 <b>Активные пользователи по журналу действий</b>\n"
        "• За 7 дней: {active_users_7_days}\n"
        "• За 30 дней: {active_users_30_days}\n"
        "• За всё время ведения журнала: {active_users_total}\n\n"
        "👨‍🏫 <b>Репетиторы и объявления</b>\n"
        "• Репетиторов, создавших объявление: {tutors_total}\n"
        "• Объявлений создано: {ads_total}\n"
        "• Опубликовано сейчас: {ads_published}\n"
        "• Ожидает проверки: {ads_on_check}\n"
        "• Отклонено: {ads_rejected}\n\n"
        "💳 <b>Покупки публикации</b>\n"
        "• Платящих репетиторов: {paying_tutors}\n"
        "• Оплаченных объявлений: {paid_ads}\n"
        "• Куплено месяцев публикации: {paid_orders}\n"
        "• Средний купленный период: {average_purchased_months:.1f} мес.\n"
        "{subscription_distribution}\n\n"
        "💰 <b>Валовая выручка</b>\n"
        "• За последние 30 дней: {revenue_30_days} ₽ "
        "({paid_orders_30_days} покупок)\n"
        "• За последние 6 месяцев: {revenue_6_months} ₽ "
        "({paid_orders_6_months} покупок)\n"
        "• За всё время: {revenue_all_time} ₽\n\n"
        "📈 <b>Вовлечённость</b>\n"
        "• Показов объявлений: {views_total}\n"
        "• Уникальных пользователей поиска: {unique_viewers}\n"
        "• Сохранений объявлений: {saves_total}\n\n"
        "⚙️ <b>Работа обработчиков за 30 дней</b>\n"
        "• Действий: {actions_30_days}\n"
        "• Ошибок: {errors_30_days}\n"
        "• Среднее время обработки: {average_processing_ms_30_days:.1f} мс"
    )
    NO_SUBSCRIPTION_DATA = "• Пока нет оплаченных периодов."
    SUBSCRIPTION_DISTRIBUTION_HEADER = "• Распределение периода на объявление:"
    SUBSCRIPTION_DISTRIBUTION_ROW = "  — {months} мес.: {percentage:.1f}% ({ads_count})"
    NO_WARNINGS = "Предупреждений пока нет."
